import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import StyledComponentsRegistry from './lib/StyledComponentRegistery';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'TradingTool',
  description: 'Generated By Mohammad Shanati',
  openGraph: {
    title: 'TradingTool',
    description: 'Generated By Mohammad Shanati',
    url: 'https://www.tradingtool.com',
    siteName: 'TradingTool',
    images: [
      {
        url: 'https://www.tradingtool.com/og-image.jpg',
        width: 800,
        height: 600,
        alt: 'TradingTool',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
};

export const viewport = 'width=device-width, initial-scale=1';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
